### ISSUE TITLE
Flair vs. PHPbb 3.3.0

### ISSUE THREAD

**Issue by bjornthv** [stevotvr/phpbb-flair#16]
Having a little issue when updating my PHPbb forum:

`Wed Jan 22 09:38:49.427293 2020] [proxy_fcgi:error] [pid 26993] [client x.x.x.x:49899] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: You have requested a non-existent service "stevotvr.flair.notification.type.flair". in /home/admin/domains/tsbgamers.eu/public_html/forum/vendor/symfony/dependency-injection/ContainerBuilder.php:1060\nStack trace:\n#0 /home/admin/domains/tsbgamers.eu/public_html/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(620): Symfony\\Component\\DependencyInjection\\ContainerBuilder->getDefinition('stevotvr.flair....')\n#1 /home/admin/domains/tsbgamers.eu/public_html/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\\Component\\DependencyInjection\\ContainerBuilder->doGet('stevotvr.flair....', 1)\n#2 /home/admin/domains/tsbgamers.eu/public_html/forum/phpbb/notification/manager.php(883): Symfony\\Component\\DependencyInjection\\ContainerBuilder->get('stevotvr.flair....')\n#3 /home/admin/domains/tsbgamers.eu/public_html/forum/phpbb/notification/manager.php(857): phpbb\\no...'`

**Comment by stevotvr** [comment]
When does this error message appear? Have you tried clearing the board cache or disabling and re-enabling the extension?
