### ISSUE TITLE
New translation on the way!

### ISSUE THREAD

**Issue by MakaryGo** [stevotvr/phpbb-flair#17]
Hi! I'm a huge fan of this extension, it is really awesome and has potential to be even better! 🥇 
As I'm using it _a lot_ on my community, which is Polish, I've decided to make a _real translation_ 😉 

So, my question is actually _how would you prefer to get it_?
Creating a PR like #1  would be most convenient for me, but I've noticed that you post other translations as `.zip` files on the [forums](https://www.phpbb.com/customise/db/extension/profile_flair/support/topic/184956), so it's totally up to you.

Cheers!

**Comment by stevotvr** [comment]
Hi! All translations should be posted in the thread at https://www.phpbb.com/customise/db/extension/profile_flair/support/topic/184956
Thanks for the support!
