### ISSUE TITLE
Beta 1.10: Images can not be added

### ISSUE THREAD

**Issue by bdux** [stevotvr/phpbb-flair#3]
When trying to add custom image to flair using the ACP, Server responds with a http 500 error upon clicking the button 'Add image':

![grafik](https://user-images.githubusercontent.com/5998059/39307567-7e085ef2-4963-11e8-9782-f4983164d749.png)

Running phpbb in a bitnami Virtualbox, phpbb Version 3.2.2.

**Comment by stevotvr** [comment]
Can you get the specific error message from the logs?

**Comment by bdux** [comment]
it looks like a file permission errror:

`[client 62.225.139.76:62373] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught phpbb\\filesystem\\exception\\filesystem_exception: CANNOT_CHANGE_FILE_PERMISSIONS in /opt/bitnami/apps/phpbb/htdocs/phpbb/filesystem/filesystem.php:127\nStack trace:\n#0 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/operator/image.php(61): phpbb\\filesystem\\filesystem->chmod('./../images/fla...', 7)\n#1 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/controller/acp_images_controller.php(78): stevotvr\\flair\\operator\\image->is_writable()\n#2 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(226): stevotvr\\flair\\controller\\acp_images_controller->add_image()\n#3 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(50): stevotvr\\flair\\acp\\main_module->images()\n#4 /opt/bitnami/apps/phpbb/htdocs/includes/functions_module.php(676): stevotvr\\flair\\acp\\main_module->main('\\\\stevotvr\\\\flair...', 'images')\n#5 /opt/bitnami/apps/phpbb/htdocs/adm/index.php(82): p_master->load_active()\n#6 {main}\n  thrown in /opt/bitnami/apps/phpbb/htdocs/phpbb/file...\n', referer: https://lastresortgaming.net/adm/index.php?sid=c4d2ed0b31848657903ef25766ed5a06&i=-stevotvr-flair-acp-main_module&mode=images
`

And further this:

`[Thu Apr 26 14:33:01.187314 2018] [proxy_fcgi:error] [pid 1012:tid 139777344853760] [client 92.192.67.122:50738] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught phpbb\\filesystem\\exception\\filesystem_exception: CANNOT_CHANGE_FILE_PERMISSIONS in /opt/bitnami/apps/phpbb/htdocs/phpbb/filesystem/filesystem.php:127\nStack trace:\n#0 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/operator/image.php(61): phpbb\\filesystem\\filesystem->chmod('./../images/fla...', 7)\n#1 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/controller/acp_images_controller.php(78): stevotvr\\flair\\operator\\image->is_writable()\n#2 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(226): stevotvr\\flair\\controller\\acp_images_controller->add_image()\n#3 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(50): stevotvr\\flair\\acp\\main_module->images()\n#4 /opt/bitnami/apps/phpbb/htdocs/includes/functions_module.php(676): stevotvr\\flair\\acp\\main_module->main('\\\\stevotvr\\\\flair...', 'images')\n#5 /opt/bitnami/apps/phpbb/htdocs/adm/index.php(82): p_master->load_active()\n#6 {main}\n  thrown in /opt/bitnami/apps/phpbb/htdocs/phpbb/file...\n'
[Thu Apr 26 14:33:01.977673 2018] [proxy_fcgi:error] [pid 1595:tid 139777453958912] [client 92.192.67.122:50740] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught phpbb\\filesystem\\exception\\filesystem_exception: CANNOT_CHANGE_FILE_PERMISSIONS in /opt/bitnami/apps/phpbb/htdocs/phpbb/filesystem/filesystem.php:127\nStack trace:\n#0 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/operator/image.php(61): phpbb\\filesystem\\filesystem->chmod('./../images/fla...', 7)\n#1 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/controller/acp_images_controller.php(78): stevotvr\\flair\\operator\\image->is_writable()\n#2 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(226): stevotvr\\flair\\controller\\acp_images_controller->add_image()\n#3 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(50): stevotvr\\flair\\acp\\main_module->images()\n#4 /opt/bitnami/apps/phpbb/htdocs/includes/functions_module.php(676): stevotvr\\flair\\acp\\main_module->main('\\\\stevotvr\\\\flair...', 'images')\n#5 /opt/bitnami/apps/phpbb/htdocs/adm/index.php(82): p_master->load_active()\n#6 {main}\n  thrown in /opt/bitnami/apps/phpbb/htdocs/phpbb/file...\n'
[Thu Apr 26 14:33:20.950910 2018] [proxy_fcgi:error] [pid 1595:tid 139777874347776] [client 92.192.67.122:50786] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught phpbb\\filesystem\\exception\\filesystem_exception: CANNOT_CHANGE_FILE_PERMISSIONS in /opt/bitnami/apps/phpbb/htdocs/phpbb/filesystem/filesystem.php:127\nStack trace:\n#0 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/operator/image.php(61): phpbb\\filesystem\\filesystem->chmod('./../images/fla...', 7)\n#1 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/controller/acp_images_controller.php(78): stevotvr\\flair\\operator\\image->is_writable()\n#2 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(226): stevotvr\\flair\\controller\\acp_images_controller->add_image()\n#3 /opt/bitnami/apps/phpbb/htdocs/ext/stevotvr/flair/acp/main_module.php(50): stevotvr\\flair\\acp\\main_module->images()\n#4 /opt/bitnami/apps/phpbb/htdocs/includes/functions_module.php(676): stevotvr\\flair\\acp\\main_module->main('\\\\stevotvr\\\\flair...', 'images')\n#5 /opt/bitnami/apps/phpbb/htdocs/adm/index.php(82): p_master->load_active()\n#6 {main}\n  thrown in /opt/bitnami/apps/phpbb/htdocs/phpbb/file...\n', referer: https://lastresortgaming.net/adm/index.php?sid=8204b6ba3b7d8cad55da32e441ee69cd&i=-stevotvr-flair-acp-main_module&mode=images
`

**Comment by stevotvr** [comment]
That should be fixed in the current snapshot. Thanks for the info.

**Comment by stevotvr** [comment]
Try this and let me know if it fixes the issue: https://github.com/stevotvr/phpbb-flair/releases/tag/v1.1.0-beta2

**Comment by bdux** [comment]
Will try and let you know. Additionally, I had to manually add the images/flair folder in the first place. Maybe that is also worth to mention. 

in the meantime I changed the permissions on that folder manually and adding images started to work. But I will test the new snapshot on another installation and let you know. Thank you!
