### ISSUE TITLE
Notify user when badge is awarded [idea]

### ISSUE THREAD

**Issue by koraldon** [stevotvr/phpbb-flair#4]
Currently a user doesn't know when he receives a badge - only if he looks under his profile in the viewtopic page or at his profile.
The idea is to use the PHPBB notification system when a user receives a badge, either manually at the ACP or when automatic condition is fulfilled (Post / Duration count)

**Comment by stevotvr** [comment]
#7

**Comment by koraldon** [comment]
Hi,
I have installed 1.2 on my production site, will report if I find bugs with this.
I have also asked Uriel when he can add the notification for automatic conditions.

**Comment by stevotvr** [comment]
I've changed this to use a queue with a cron job to prevent spamming people when an admin adds many of the same item in a short period. I also added support for automatic assignments. Maybe I should do that for group assignments too.

**Comment by stevotvr** [comment]
I just released a beta version that includes this feature:
https://github.com/stevotvr/phpbb-flair/releases/tag/v1.2.0-beta1
