### ISSUE TITLE
Control number of badges shown on viewtopic page [idea]

### ISSUE THREAD

**Issue by koraldon** [stevotvr/phpbb-flair#5]
Currently all the badges a user has, are shown on the user profile pane in the viewtopic page.
This idea is to allow the forum admin to limit the amount of badges shown in the viewtopic page, via a setting in the ACP. 

**Implementation thoughts:** 
The ACP controls should be enable/disable and if enabled what is the number of badges shown. For brevity sake, all badge categories (and uncategorized) should have the same "rule".
In addition, a "featured" state should be added to the badges. 
The user can select which badges are "featured" and shown on the viewtopic page via the UCP - this will require a new UCP menu item to control the badges.
Until the limit is reached for a user, all new badges should be considered "featured" automatically. 

Thoughts?

**Comment by koraldon** [comment]
A question regarding this, what do you think is the best way to control this - Is a "featured" state good with you? 
I assume it should be in the Database or something like that... If you have thoughts on the best architecture it will be great, so Uriel will know what is the best approach to implement.

**Comment by stevotvr** [comment]
I guess you would just add a boolean field to the database to indicate that an item is featured and then sort by that.

**Comment by koraldon** [comment]
Hi,
Should I ask Uriel when he has time for this? Or does someone else works on this?

**Comment by stevotvr** [comment]
I don't see any new forks so I don't think anyone else is working on this.

**Comment by stevotvr** [comment]
I will start working on this now.

**Comment by stevotvr** [comment]
I just released a beta version that includes this feature:
https://github.com/stevotvr/phpbb-flair/releases/tag/v1.2.0-beta1
