### ISSUE TITLE
Add "free" badges [idea]

### ISSUE THREAD

**Issue by koraldon** [stevotvr/phpbb-flair#6]
Currently all badges are either awarded manually in the ACP or when the members reaches some "automatic" condition.
The suggestion is to designate badges as either "public/free" or "limited/private". 
The limited badges, are awarded in exactly the same way as before.
The public/free badges, can either be awarded in the ACP/automatically or the user can select to add them to his badges, freely, from the UCP. This requires an element in the UCP, which is also required for #5 
This should be implemented IMHO after #5 

This will be great for a lot of sites. Mine is a gaming site, so I can add badges for fans of D&D/RPG/Boardgames/etc... Sport sites can add badges for sports teams and so on.

**Comment by stevotvr** [comment]
I will start working on this feature now.

**Comment by stevotvr** [comment]
I just released a beta version that includes this feature:
https://github.com/stevotvr/phpbb-flair/releases/tag/v1.2.0-beta1

**Comment by koraldon** [comment]
Awesome! 
Just to make sure, before I install it - can you select part of the badges to be "free" and part of them to be "limited"? 
It is not clear from the description if it is a global toggle or per flair.
Cheers :)

**Comment by stevotvr** [comment]
When you select the groups to assign flair to, there is an option to automatically assign the flair. If you choose No, the members of the groups can manually add it in the Profile panel of the UCP. So it is per item.

**Comment by koraldon** [comment]
Hi,
So just to understand, let's say I have three free badges: Xbox, PlayStation and Nintendo switch. In addition I have a premium/limited badge for champion of the month.
So if a user wants to have the Xbox and PS badges, I need to assign them to the "registered" group and than he can pick them up?

**Comment by stevotvr** [comment]
Correct
